name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - vue-dev
  pull_request:
    branches:
      - vue-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'vite-vue-mcisee/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd vite-vue-mcisee
          npm ci
      
      - name: Build Vue app
        run: |
          cd vite-vue-mcisee
          npm run build
      
      - name: Setup Pages
        if: github.ref == 'refs/heads/vue-dev'
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        if: github.ref == 'refs/heads/vue-dev'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'vite-vue-mcisee/dist'
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/vue-dev'
        id: deployment
        uses: actions/deploy-pages@v4

# Grant GITHUB_TOKEN the permissions required to deploy to Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false